local loader = require("helpers.load_addon")

describe("B11 sandbox lifecycle", function()
  it("clones, re-enters, refreshes, resets, and exits without changing production", function()
    local _, dibs = loader.load({ wow = { guildLeader = true } })
    dibs.DeveloperMode.SetEnabled(true)
    local before = loader.snapshotProductionState(dibs)

    local ok, context = dibs.DeveloperSandbox.EnterSandbox({ clone = true, role = "guild_master" })
    assert_true(ok)
    assert_equal("sandbox", context.provider)
    assert_equal("guild_master", context.role)
    assert_equal("simulated_sandbox", context.authorityOrigin)
    assert_equal("sandbox", dibs.DeveloperSandbox.GetActiveProvider())

    assert_true(dibs.DeveloperSandbox.SetRole("officer"))
    assert_true(dibs.DeveloperSandbox.RefreshSandbox())
    assert_true(dibs.DeveloperSandbox.ResetSandbox())
    assert_true(dibs.DeveloperSandbox.ExitSandbox())
    assert_equal("production", dibs.DeveloperSandbox.GetActiveProvider())
    assert_true(loader.productionStateEquals(dibs, before), "sandbox operations must not mutate production state")

    local retained = dibs.DeveloperSandboxStore.GetPersisted()
    assert_not_nil(retained)
    local _, reloaded = loader.load({ wow = { guildLeader = true }, sandboxVariables = retained })
    assert_false(reloaded.DeveloperSandbox.IsActive())
    assert_equal("production", reloaded.DeveloperSandbox.GetActiveProvider())
    reloaded.DeveloperMode.SetEnabled(true)
    assert_true(reloaded.DeveloperSandbox.EnterSandbox())
    assert_equal("sandbox", reloaded.DeveloperSandbox.GetActiveProvider())
  end)
end)