describe("Backup, import/export and profiles", function()
  local loader, dibs
  before_each(function()
    loader = require("helpers.load_addon")
    _, dibs = loader.load({ wow = { guildLeader = true } })
  end)

  it("exports a versioned local package and validates its checksum", function()
    local text, package = dibs.ImportExport.Export("local")
    assert_not_nil(text); assert_equal("local", package.scope)
    local decoded = dibs.ImportExport.Decode(text)
    assert_not_nil(decoded); assert_equal(package.checksum, decoded.checksum)
    local bad = text:sub(1, -2) .. "x"
    assert_nil(dibs.ImportExport.Decode(bad))
  end)

  it("rejects malformed, truncated and future package fixtures", function()
    local fixtures = require("helpers.package_fixtures")
    assert_nil(dibs.ImportExport.Decode(fixtures.invalidPrefix))
    assert_nil(dibs.ImportExport.Decode(fixtures.emptyPackage))
    assert_nil(dibs.ImportExport.Decode(fixtures.truncatedPackage))
    assert_nil(dibs.ImportExport.Decode(fixtures.futureSchema))
  end)

  it("rejects executable-looking package content", function()
    local text = dibs.ImportExport.Export("local")
    assert_not_nil(text)
    local package = dibs.ImportExport.Decode(text)
    package.payload.presentation.theme = "/run evil"
    local body = "DIBS-PKG-1|" .. "{}"
    assert_nil(dibs.ImportExport.Decode(body))
  end)

  it("creates a safety snapshot before restoring a preview", function()
    local db = dibs.GetDB(); db.settings.theme = "before"
    local snapshot = dibs.Backup.Create("local", "test")
    assert_not_nil(snapshot)
    db.settings.theme = "after"
    local preview = dibs.Backup.PreviewRestore(snapshot.snapshotId)
    assert_not_nil(preview); assert_equal("after", db.settings.theme)
    dibs.Backup.Restore(preview.previewId, true, "test")
    assert_equal("before", db.settings.theme)
    assert_true(#dibs.Backup.List() >= 2)
  end)

  it("keeps profile operations independent from ledger balances", function()
    local season = dibs.GetCurrentSeasonId(); dibs.Ledger.Grant("Tester-Realm", 1, "test", "test", season)
    local before = #dibs.Ledger.GetAllTransactions()
    local profile = dibs.Profiles.Create("Test profile", "local")
    assert_not_nil(profile); assert_not_nil(dibs.Profiles.Activate("Test profile", "local"))
    assert_equal(before, #dibs.Ledger.GetAllTransactions())
    assert_true(dibs.Profiles.Delete("Test profile", "local"))
  end)

  it("previews and applies a guild configuration package", function()
    local text = dibs.ImportExport.Export("guild")
    assert_not_nil(text)
    local preview = dibs.ImportExport.Preview(text, "guild", "merge")
    assert_not_nil(preview)
    assert_equal("pending", preview.decision)
    local result = dibs.ImportExport.Apply(preview.previewId, true, "test")
    assert_equal("confirmed", result.decision)
  end)

  it("appends full ledger data idempotently", function()
    local season = dibs.GetCurrentSeasonId()
    dibs.Ledger.Grant("Tester-Realm", 1, "portable", "test", season)
    local text = dibs.ImportExport.Export("full")
    local preview = dibs.ImportExport.Preview(text, "full", "append")
    local count = #dibs.Ledger.GetAllTransactions()
    local applied = dibs.ImportExport.Apply(preview.previewId, true, "test")
    assert_equal("confirmed", applied.decision)
    assert_equal(count, #dibs.Ledger.GetAllTransactions())
  end)
end)
