local loader = require("helpers.load_addon")
local wow = require("helpers.wow_api")

describe("Raid entry prompts", function()
  it("requires opt-in and explicit acceptance without request or ledger changes", function()
    local _, dibs = loader.load({ wow = { guildLeader = true, inRaid = true, instanceName = "Test Raid", instanceType = "raid", instanceId = 100 } })
    local before = #dibs.PreDibs.GetHistory()
    assert_false(dibs.RaidPrompts.OnEvent("PLAYER_ENTERING_WORLD"))
    dibs.RaidPrompts.SetEnabled(true)
    assert_true(dibs.RaidPrompts.OnEvent("PLAYER_ENTERING_WORLD"))
    assert_true(dibs.RaidPrompts.Accept())
    assert_equal(100, _G.__ejNavigation.instanceId)
    assert_equal(before, #dibs.PreDibs.GetHistory())
  end)

  it("defers prompts in combat and revalidates after combat", function()
    local _, dibs = loader.load({ wow = { guildLeader = true, inRaid = true, inCombat = true, instanceType = "raid", instanceId = 100 } })
    dibs.RaidPrompts.SetEnabled(true)
    local shown, reason = dibs.RaidPrompts.OnEvent("PLAYER_ENTERING_WORLD")
    assert_false(shown)
    assert_equal("DEFERRED_COMBAT", reason)
    wow.setCombat(false)
    assert_true(dibs.RaidPrompts.OnEvent("PLAYER_REGEN_ENABLED"))
  end)

  it("registers prompt and roster events through AceEvent when available", function()
    local _, dibs = loader.load({ wow = { guildLeader = true, inRaid = true, instanceType = "raid", instanceId = 100 }, withAce3 = true })
    assert_not_nil(dibs.Ace3.libs.event.handlers.PLAYER_ENTERING_WORLD)
    assert_not_nil(dibs.Ace3.libs.event.handlers.PLAYER_REGEN_ENABLED)
    assert_not_nil(dibs.Ace3.libs.event.handlers.GROUP_ROSTER_UPDATE)
  end)
end)