local loader = require("helpers.load_addon")

describe("First installation assistant UI", function()
  it("mounts the setup route as one Officer-owned page", function()
    local _, dibs = loader.load({ wow = { guildLeader = true }, withAce3 = true })
    local frame = dibs.OfficerUI.CreateWindow("setup")
    assert_equal("setup", frame.selectedRoute)
    assert_equal("setup", frame.mountedPage)
    assert_equal(1, frame.primaryPageCount)
    assert_true(frame.contentHost._dibsCurrentPageRoot ~= nil)
  end)

  it("routes channel setup to Guild Rules announcements", function()
    local _, dibs = loader.load({ wow = { guildLeader = true }, withAce3 = true })
    local frame = dibs.OfficerUI.CreateWindow("setup")
    frame:ActivateRoute("announcements")
    assert_equal("announcements", frame.activeTab)
    assert_equal("announcements", frame.selectedRoute)
    assert_true(frame.activeTab ~= "overview")
  end)
end)
