local loader = require("helpers.load_addon")
local fixtures = require("helpers.dispute_fixtures")

describe("Dispute authority and privacy contract", function()
  it("persists status and timeline across a request read", function()
    local _, dibs = loader.load({ wow = { guildLeader = true }, withAce3 = true })
    local request = dibs.Disputes.CreateReport({ category = "other", note = string.rep("x", 500) })
    assert_true(#request.note <= dibs.Disputes.MAX_NOTE_LENGTH)
    local result = dibs.Disputes.Resolve(request.requestId, "no correction", { reason = "Evidence is valid" }, nil)
    assert_true(result.ok)
    local timeline = dibs.Disputes.GetTimeline(request.requestId, nil)
    assert_true(#timeline >= 2)
    assert_equal("Resolved", dibs.Disputes.GetRequest(request.requestId, nil).status)
  end)

  it("does not grant review authority to raid roles", function()
    local _, dibs = loader.load({ wow = { guildLeader = false, guildRankIndices = { [1] = 3 }, raidLeader = true, raidAssistant = true, masterLoot = true }, withAce3 = true })
    local request = dibs.Disputes.CreateReport({ category = "other" })
    assert_not_nil(request)
    local queue, reason = dibs.Disputes.ListForOfficer("Tester-Realm")
    assert_equal(0, #queue)
    assert_equal("GUILD_ADMIN_REQUIRED", reason)
    local result, resolveReason = dibs.Disputes.Resolve(request.requestId, "no correction", { reason = "No issue" }, "Tester-Realm")
    assert_nil(result)
    assert_equal("GUILD_ADMIN_REQUIRED", resolveReason)
  end)

  it("keeps the timeline append-only and isolates guild scopes", function()
    local _, dibs = loader.load({ wow = { guildLeader = true }, withAce3 = true })
    local request = dibs.Disputes.CreateReport(fixtures.report("other"))
    local firstEvent = request.timeline[1].eventId
    local reviewed = dibs.Disputes.BeginReview(request.requestId, nil)
    assert_true(reviewed.ok)
    local resolved = dibs.Disputes.NoCorrection(request.requestId, "Confirmed by Officer", nil)
    assert_true(resolved.ok)
    local timeline = dibs.Disputes.GetTimeline(request.requestId, nil)
    assert_true(#timeline >= 3)
    assert_equal(firstEvent, timeline[1].eventId)
    dibs.GetGuildKey = function() return "guild:new" end
    local queue, reason = dibs.Disputes.ListForOfficer(nil)
    assert_equal(0, #queue)
    assert_equal(nil, reason)
    assert_nil(dibs.Disputes.GetRequest(request.requestId, nil))
  end)

  it("survives a SavedVariables reload without changing the request", function()
    local _, firstDibs = loader.load({ wow = { guildLeader = true }, withAce3 = true })
    local request = firstDibs.Disputes.CreateReport(fixtures.report("other", { note = "Keep this audit" }))
    local saved = firstDibs.GetDB()
    local _, reloaded = loader.load({ wow = { guildLeader = true }, savedVariables = saved, withAce3 = true })
    local restored = reloaded.Disputes.GetRequest(request.requestId, "Tester-Realm")
    assert_not_nil(restored)
    assert_equal("Keep this audit", restored.note)
    assert_equal("Open", restored.status)
  end)

  it("rejects a second terminal decision without appending another event", function()
    local _, dibs = loader.load({ wow = { guildLeader = true }, withAce3 = true })
    local request = dibs.Disputes.CreateReport({ category = "other" })
    local first = dibs.Disputes.NoCorrection(request.requestId, "No accounting change", nil)
    assert_true(first.ok)
    local before = #dibs.Disputes.GetTimeline(request.requestId, nil)
    local second, reason = dibs.Disputes.NoCorrection(request.requestId, "Repeat", nil)
    assert_nil(second)
    assert_equal("REQUEST_ALREADY_RESOLVED", reason)
    assert_equal(before, #dibs.Disputes.GetTimeline(request.requestId, nil))
  end)
end)
