local loader = require("helpers.load_addon")

describe("Encounter Journal UI contract", function()
  it("keeps unknown categories allowed and recommended non-Dib categories blocked", function()
    local _, dibs = loader.load({ wow = { guildLeader = true } })
    assert_true(dibs.EncounterJournal.IsSubCategoryAllowed("UNKNOWN"))
    assert_false(dibs.EncounterJournal.IsSubCategoryAllowed("COSMETIC"))
    assert_false(dibs.EncounterJournal.IsSubCategoryAllowed("DECOR"))
    assert_false(dibs.EncounterJournal.IsSubCategoryAllowed("MOUNT"))
  end)

  it("uses normalized category keys for overrides", function()
    local _, dibs = loader.load({ wow = { guildLeader = true } })
    local key = dibs.EncounterJournal.SetSubCategoryAllowed("  cosmetic ", true)
    assert_equal("COSMETIC", key)
    assert_true(dibs.EncounterJournal.IsSubCategoryAllowed("COSMETIC"))
  end)

  it("handles sub-category slash overrides without raising an error", function()
    local _, dibs = loader.load({ wow = { guildLeader = true } })

    assert_true(pcall(dibs.EncounterJournal.HandleSubCategorySlash, "allow COSMETIC"))
    assert_true(dibs.EncounterJournal.IsSubCategoryAllowed("COSMETIC"))
    assert_true(pcall(dibs.EncounterJournal.HandleSubCategorySlash, "block COSMETIC"))
    assert_false(dibs.EncounterJournal.IsSubCategoryAllowed("COSMETIC"))
    assert_true(pcall(dibs.EncounterJournal.HandleSubCategorySlash, "clear"))
  end)

  it("does not let an ordinary player change the shared category policy", function()
    local _, dibs = loader.load({ wow = { guildLeader = false, guildMembers = { "Tester-Realm" }, guildRankIndices = { [1] = 3 } } })
    local key, reason = dibs.EncounterJournal.SetSubCategoryAllowed("COSMETIC", true)
    assert_nil(key)
    assert_equal("GUILD_ADMIN_REQUIRED", reason)
    assert_false(dibs.EncounterJournal.IsSubCategoryAllowed("COSMETIC"))
  end)
end)
