local loader = require("helpers.load_addon")

describe("B11g accessibility presentation", function()
  it("distinguishes semantic states with readable labels and markers", function()
    local _, dibs = loader.load()
    local ready = dibs.Midnight.GetStatusPresentation("ready")
    local warning = dibs.Midnight.GetStatusPresentation("warning")
    local danger = dibs.Midnight.GetStatusPresentation("danger")
    assert_equal("Ready", ready.label)
    assert_equal("[OK]", ready.marker)
    assert_equal("Warning", warning.label)
    assert_equal("[!]", warning.marker)
    assert_equal("Action required", danger.label)
    assert_equal("[X]", danger.marker)
    assert_true(ready.explanation ~= warning.explanation)
  end)

  it("raises text and border contrast without changing the Midnight theme", function()
    local _, dibs = loader.load()
    dibs.Midnight.SetProfile({ contrast = "high", scale = 1.4 })
    local tokens = dibs.Midnight.GetTokens()
    assert_equal("MIDNIGHT", tokens.theme)
    assert_equal("high", tokens.contrast)
    assert_equal(1.4, tokens.scale)
    assert_equal(1, tokens.colors.TEXT[1])
    assert_true(tokens.colors.BORDER[1] >= 0.6)
    assert_nil(dibs.GetDB().presentation)
  end)

  it("keeps semantic status presentation independent from color-only metadata", function()
    local _, dibs = loader.load()
    local presentation = dibs.Midnight.GetStatusPresentation("info")
    assert_true(type(presentation.label) == "string" and presentation.label ~= "")
    assert_true(type(presentation.marker) == "string" and presentation.marker ~= "")
    assert_true(type(presentation.explanation) == "string" and presentation.explanation ~= "")
    assert_equal("info", presentation.tone)
  end)
end)
