local loader = require("helpers.load_addon")
local mocks = require("helpers.b11_ui_mocks")

describe("B11a Midnight tokens", function()
  after_each(function() mocks.clear() end)

  it("loads one Midnight theme with centralized semantic tokens", function()
    local _, dibs = loader.load()
    local tokens = dibs.Midnight.GetTokens()
    assert_equal("MIDNIGHT", tokens.theme)
    assert_not_nil(tokens.colors.PRIMARY)
    assert_not_nil(tokens.colors.SUCCESS)
    assert_true(tokens.sizing.minWidth >= 420)
    assert_true(tokens.typography.body >= 12)
  end)

  it("uses LibSharedMedia when available and falls back when media is missing", function()
    local _, dibs = loader.load()
    local previous = _G.LibStub
    mocks.installLibraries(previous)
    dibs.Midnight.SetProfile({ fontName = "Test Font", statusbarName = "Test Bar" })
    local tokens = dibs.Midnight.GetTokens()
    assert_equal("Interface\\Fonts\\Test.ttf", tokens.typography.font)
    assert_equal("Interface\\Textures\\Test", tokens.surfaces.statusbar)
    dibs.Midnight.SetProfile({ fontName = "Missing", statusbarName = "Missing" })
    tokens = dibs.Midnight.GetTokens()
    assert_equal("Fonts\\FRIZQT__.TTF", tokens.typography.font)
    assert_equal("Interface\\TargetingFrame\\UI-StatusBar", tokens.surfaces.statusbar)
  end)

  it("bounds local scale and supports high contrast without changing theme", function()
    local _, dibs = loader.load()
    dibs.Midnight.SetProfile({ scale = 9, contrast = "high" })
    local tokens = dibs.Midnight.GetTokens()
    assert_equal(1.5, tokens.scale)
    assert_equal("high", tokens.contrast)
    assert_equal("MIDNIGHT", tokens.theme)
    assert_equal(1, tokens.colors.TEXT[1])
  end)
end)
