local loader = require("helpers.load_addon")
local mocks = require("helpers.b11_ui_mocks")

describe("B11a Midnight tokens", function()
  after_each(function() mocks.clear() end)

  it("loads one Midnight theme with centralized semantic tokens", function()
    local _, dibs = loader.load()
    local tokens = dibs.Midnight.GetTokens()
    assert_equal("MIDNIGHT", tokens.theme)
    assert_not_nil(tokens.colors.PRIMARY)
    assert_not_nil(tokens.colors.SUCCESS)
    assert_true(tokens.sizing.minWidth >= 420)
    assert_true(tokens.typography.body >= 12)
  end)

  it("exposes isolated color variants without changing the active theme", function()
    local _, dibs = loader.load()
    local names = dibs.Midnight.GetThemeNames()
    assert_equal(5, #names)
    assert_equal("MIDNIGHT", names[1])
    assert_equal("ARCANE_VIOLET", names[4])

    local palette = dibs.Midnight.GetThemePalette("FEL_GREEN")
    assert_not_nil(palette)
    assert_not_nil(palette.PRIMARY)
    assert_not_nil(palette.SURFACE)
    palette.PRIMARY[1] = 0
    assert_true(dibs.Midnight.GetThemePalette("FEL_GREEN").PRIMARY[1] > 0)
    local preview = dibs.Midnight.GetThemeTokens("FROST_STEEL")
    assert_equal("FROST_STEEL", preview.theme)
    assert_true(preview.sizing.minWidth >= 420)
    assert_equal("MIDNIGHT", dibs.Midnight.GetTokens().theme)
    assert_nil(dibs.Midnight.GetThemePalette("UNKNOWN"))
  end)

  it("uses LibSharedMedia when available and falls back when media is missing", function()
    local _, dibs = loader.load()
    local previous = _G.LibStub
    mocks.installLibraries(previous)
    dibs.Midnight.SetProfile({ fontName = "Test Font", statusbarName = "Test Bar" })
    local tokens = dibs.Midnight.GetTokens()
    assert_equal("Interface\\Fonts\\Test.ttf", tokens.typography.font)
    assert_equal("Interface\\Textures\\Test", tokens.surfaces.statusbar)
    dibs.Midnight.SetProfile({ fontName = "Missing", statusbarName = "Missing" })
    tokens = dibs.Midnight.GetTokens()
    assert_equal("Fonts\\FRIZQT__.TTF", tokens.typography.font)
    assert_equal("Interface\\TargetingFrame\\UI-StatusBar", tokens.surfaces.statusbar)
  end)

  it("bounds local scale and supports high contrast without changing theme", function()
    local _, dibs = loader.load()
    dibs.Midnight.SetProfile({ scale = 9, contrast = "high" })
    local tokens = dibs.Midnight.GetTokens()
    assert_equal(1.5, tokens.scale)
    assert_equal("high", tokens.contrast)
    assert_equal("MIDNIGHT", tokens.theme)
    assert_equal(1, tokens.colors.TEXT[1])
  end)
end)
