local loader = require("helpers.load_addon")

describe("Permissions", function()
  it("returns invalid action for malformed action id", function()
    local _, dibs = loader.load({ wow = { guildLeader = true } })
    local decision = dibs.Permissions.Evaluate(nil)
    assert_false(decision.allowed)
    assert_equal("INVALID_ACTION", decision.reasonCode)
  end)

  it("authorizes guild officers for Dibs administration in standalone mode", function()
    local _, dibs = loader.load({ wow = { guildLeader = false, guildMembers = { "Tester-Realm" }, guildRankIndices = { [1] = 1 } } })
    assert_true(dibs.Permissions.IsOfficer())
    assert_true(dibs.Permissions.Can("ledger.grant"))
    assert_true(dibs.Permissions.Can("predib.mode.set"))
  end)

  it("does not treat ML or raid roles as Dibs administrators", function()
    local rc = loader.makeRCLootCouncil({ enabled = true, masterLooter = { guid = "Player-1-TESTER", name = "Tester-Realm" } })
    local _, dibs = loader.load({ rclootcouncil = rc, wow = { guildLeader = false, guildMembers = { "Tester-Realm" }, guildRankIndices = { [1] = 3 }, inRaid = true, raidLeader = true, raidAssistant = true } })
    assert_false(dibs.Permissions.Can("ledger.grant"))
    assert_equal("GUILD_ADMIN_REQUIRED", dibs.Permissions.Evaluate("ledger.grant").reasonCode)
    local canRemind = dibs.Permissions.CanSendReminder()
    assert_true(canRemind)
  end)

  it("keeps the guild master able to administer Dibs while another player is ML", function()
    local rc = loader.makeRCLootCouncil({ enabled = true, masterLooter = { guid = "Player-2-ML", name = "Other-Realm" } })
    local _, dibs = loader.load({ rclootcouncil = rc, wow = { guildLeader = true } })
    assert_true(dibs.Permissions.Can("ledger.adjust"))
  end)

  it("allows only a verified RCLootCouncil ML to send a non-accounting reminder", function()
    local rc = loader.makeRCLootCouncil({ enabled = true, masterLooter = { guid = "Player-1-TESTER", name = "Tester-Realm" } })
    local _, dibs = loader.load({ rclootcouncil = rc, wow = { guildLeader = false, guildMembers = { "Tester-Realm" }, guildRankIndices = { [1] = 3 }, inRaid = true } })
    local canRemind = dibs.Permissions.CanSendReminder()
    assert_true(canRemind)

    local _, standalone = loader.load({ wow = { guildLeader = false, guildMembers = { "Tester-Realm" }, guildRankIndices = { [1] = 3 }, inRaid = true, masterLooter = true } })
    local standaloneCanRemind, reason = standalone.Permissions.CanSendReminder()
    assert_false(standaloneCanRemind)
    assert_equal("REMINDER_NOT_AUTHORIZED", reason)
  end)

  it("protects shared settings and installation mode from ordinary players", function()
    local _, dibs = loader.load({ wow = { guildLeader = false, guildMembers = { "Tester-Realm" }, guildRankIndices = { [1] = 3 } } })
    assert_nil(dibs.PreDibs.SetAnnouncementTemplates("forged", nil))
    assert_nil(dibs.RCLootCouncil.SetDibEnabledForType("MOUNTS", false))
    local debugLevel, debugReason = dibs.SetDebugLevel("all", 5)
    assert_nil(debugLevel)
    assert_equal("GUILD_ADMIN_REQUIRED", debugReason)
    local prompts, promptReason = dibs.RaidPrompts.SetEnabled(true)
    assert_nil(prompts)
    assert_equal("GUILD_ADMIN_REQUIRED", promptReason)
    local announcementDebug, announcementReason = dibs.PreDibs.SetAnnouncementDebug(true)
    assert_nil(announcementDebug)
    assert_equal("GUILD_ADMIN_REQUIRED", announcementReason)
    local mode = dibs.ProtectedActions.Execute("installation.mode.set", nil, { mode = "STANDALONE" })
    assert_false(mode.ok)
    assert_equal("GUILD_ADMIN_REQUIRED", mode.reasonCode)
  end)
end)
