local loader = require("helpers.load_addon")

describe("Pre-Dib requests", function()
  it("stores request metadata and reuses an active duplicate", function()
    local _, dibs = loader.load({ wow = { guildLeader = true } })
    local seasonId = dibs.GetCurrentSeasonId()
    local first = dibs.PreDibs.CreatePublic("Tester-Realm", 21011, "Item 21011", seasonId, "test")
    local second = dibs.PreDibs.CreatePublic("Tester-Realm", 21011, "Item 21011", seasonId, "test")

    assert_not_nil(first)
    assert_equal(first.requestId, second.requestId)
    assert_equal(seasonId, first.seasonId)
    assert_equal("Tester-Realm", first.playerName)
    assert_equal(21011, first.itemID)
    assert_equal("confirmed", first.status)
    assert_equal(1, #dibs.PreDibs.GetHistory())
  end)

  it("returns stable reasons for invalid public requests", function()
    local _, dibs = loader.load({ wow = { guildLeader = true } })
    local invalid, invalidReason = dibs.PreDibs.CreatePublic("Tester-Realm", 0, "Invalid", dibs.GetCurrentSeasonId(), "test")
    assert_nil(invalid)
    assert_equal("INVALID_ITEM", invalidReason)

    dibs.GetDB().settings.allowPublicPreDibs = false
    local disabled, disabledReason = dibs.PreDibs.CreatePublic("Tester-Realm", 21012, "Item", dibs.GetCurrentSeasonId(), "test")
    assert_nil(disabled)
    assert_equal("PUBLIC_PRE_DIBS_DISABLED", disabledReason)
  end)

  it("enforces Encounter mode only for matching current raid loot", function()
    local _, dibs = loader.load({ wow = { guildLeader = true } })
    local seasonId = dibs.GetCurrentSeasonId()
    dibs.PreDibs.SetModePolicy(seasonId, "ENCOUNTER")
    local outside, outsideReason = dibs.PreDibs.CreatePublic("Tester-Realm", 21013, "Item", seasonId, "test")
    local matched = dibs.PreDibs.CreatePublic("Tester-Realm", 21013, "Item", seasonId, "test", { inRaid = true, raidId = 10, itemRaidId = 10 })
    local mismatch, mismatchReason = dibs.PreDibs.CreatePublic("Tester-Realm", 21014, "Item", seasonId, "test", { inRaid = true, raidId = 10, itemRaidId = 20 })

    assert_nil(outside)
    assert_equal("ENCOUNTER_REQUIRES_RAID", outsideReason)
    assert_not_nil(matched)
    assert_nil(mismatch)
    assert_equal("ENCOUNTER_RAID_MISMATCH", mismatchReason)
  end)

  it("keeps active requests separate by normalized difficulty", function()
    local _, dibs = loader.load({ wow = { guildLeader = true } })
    local seasonId = dibs.GetCurrentSeasonId()
    local normal = dibs.PreDibs.CreatePublic("Tester-Realm", 21015, "Item", seasonId, "test", { difficulty = 14 })
    local heroic = dibs.PreDibs.CreatePublic("Tester-Realm", 21015, "Item", seasonId, "test", { difficulty = "heroic" })
    local repeatedHeroic = dibs.PreDibs.CreatePublic("Tester-Realm", 21015, "Item", seasonId, "test", { difficulty = 15 })

    assert_equal("Normal", normal.difficulty)
    assert_equal("Heroic", heroic.difficulty)
    assert_equal(heroic.requestId, repeatedHeroic.requestId)
    assert_equal(2, #dibs.PreDibs.GetHistory())
  end)

  it("records Vault acquisitions without changing requests or ledger", function()
    local _, dibs = loader.load({ wow = { guildLeader = true } })
    local seasonId = dibs.GetCurrentSeasonId()
    local request = dibs.PreDibs.CreatePublic("Tester-Realm", 21016, "Item", seasonId, "test", { difficulty = "Mythic" })
    local ledgerCount = #dibs.Ledger.GetAllTransactions()
    local acquisition = dibs.PreDibs.RecordVaultAcquisition("Tester-Realm", 21016, "Heroic")

    assert_equal("VAULT", acquisition.source)
    assert_equal("Heroic", acquisition.difficulty)
    assert_equal("confirmed", request.status)
    assert_equal(1, #dibs.PreDibs.GetHistory())
    assert_equal(ledgerCount, #dibs.Ledger.GetAllTransactions())
    assert_equal(1, #dibs.PreDibs.GetAcquisitionsForItem(21016))
  end)
end)
