local loader = require("helpers.load_addon")

describe("Standalone admins", function()
  it("keeps legacy appointments historical without granting authority", function()
    local _, dibs = loader.load({ wow = { guildLeader = true } })
    local appoint = dibs.ProtectedActions.Execute("admin.appoint", nil, { target = "Alt-Realm", reason = "test" })
    assert_true(appoint.ok)
    local decision = dibs.Permissions.Evaluate("ledger.grant", { name = "Alt-Realm" })
    assert_false(decision.allowed)
    assert_equal("GUILD_ADMIN_REQUIRED", decision.reasonCode)
    assert_equal("guild", decision.authority)
  end)
end)
